# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Azure for developers"
email: programistkaikot@gmail.com
description: "Azure for Developers cours page."
baseurl: "/AzureForDevelopers"
url: "https://jlamch.net"
twitter_username: "jlamch"
github_username:  "jlamch"
color_theme:  "#765B8A"
color_text:  "#fff"
language:  "en"

# Build settings
markdown: kramdown
permalink: /:title/
gems: [jekyll-paginate]
paginate: 5

# Plugins
plugins_dir:
  - jekyll-admin
